inherit_from: .rubocop_todo.yml

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: false
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/Lambda:
  EnforcedStyle: line_count_dependent
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
