inherit_from: .rubocop_todo.yml

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true  

Layout/SpaceAroundOperators:
  AllowForAlignment: true
  EnforcedStyleForExponentOperator: no_space
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  Enabled: true

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: true
  Enabled: true

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact
  EnforcedStyleForEmptyBraces: no_space
  Enabled: true

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: false
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/Lambda:
  EnforcedStyle: line_count_dependent
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
